### ISSUE TITLE
DJI SDK cannot detect the connection between mobile device and remote controller randomly on iOS 11 Beta 5

### ISSUE THREAD

**Issue by lbj96347** [dji-sdk/Mobile-SDK-iOS#143]
Description of the issues
====================

Since Apple had release iOS 11 Beta 5, it means that the GM version will be coming soon. Maybe next month iOS 11 will be released on this planet. I tried to test DJI SDK on iOS 11 and found a weird issue in connection part. Sometimes it can detect the connection between mobile device and remote controller and I can see the aircraft info. But I can't see the image-transmission buffer.  

Steps to reproduce the bug or crash issues
==================================

After the activation process of DJI SDK, I will get the aircraft name and some aircraft info. But I can't get the image-transmission buffer.

When I met this issue I tried to unplug the USB cable then plug it into remote controller again. After several times, it works. 

I also tried to open DJI GO 4 to check around when I met this issue. I can see in DJI GO 4 it shows the connection between remote controller and aircraft is disconnect. If I plug USB cable again, it works. I test in iOS 10 devices with the same cable and remote controller, it works well.

Devices and SDK info
=================
-  DJI iOS SDK : 4.2.2 
-  DJI Product : Phantom 4 Advanced
-  iOS system version : iOS 11 Beta 5
-  iOS device type : iPad Pro 10", iPhone 7 Plus 
-  Xcode version : Version 9.0 beta 5 (9M202q)

**Comment by peteboothroyd** [comment]
I'm getting the same issue. I think that I've tracked the root cause down. Since XCode 9 apple has introduced a [main thread checker](https://developer.apple.com/documentation/code_diagnostics/main_thread_checker), in various parts of the video previewer code the UI is updated from a background thread, producing an error.
See discussion [here](https://stackoverflow.com/questions/44391367/swift-4-uiapplication-registerforremotenotifications-must-be-called-from-mai). 
As one of the answers describes above you can turn of this feature by going to Product->Scheme->Edit Scheme->Run->Diagnostics and unchecking the 'Main Thread Checker' box. This has worked for me but seems flakey. 
### EDIT
I have been able to get the video preview view to work with the main thread checker enabled. Again this seems unreliable. 
Do you have any idea when this will be updated in the SDK?

**Comment by XietongLU** [comment]
@peteboothroyd Thanks for your input. That's also what we found and we will provide a temp fix shortly. We will try to find a better solution in the following days.

**Comment by madamm91** [comment]
Same here. When I start my application, the feed doesn't appear. As I see there are two problems. Sometimes the camera object of DJIAircraft is nil (swift).  That is one thing. But when the connection is ok, and the camera is not nil, then I can't see the video feed of the drone but! when I get a snapshot from the videoPreviewer then I get the appropriate picture.

When there is no video feed, I can do the following: 
- Switch to the DJI GO 4 application
- Reconnect the drone using lightning port
- Wait till the feed appears in DJI GO 4
- Switch back to my application, and wait 2-3 seconds to the feed. (Sometimes reconnecting the drone is needed)

Devices and SDK info

DJI iOS SDK : 4.2.2
DJI Product : Mavic Pro
iOS system version : iOS 11 Beta 5
iOS device type : iPhone 7
Xcode version : Version 9.0 beta 5 (9M202q)

**Comment by oliverou** [comment]
Hi @lbj96347 @peteboothroyd  @madamm91, we have fixed this issue in the Video Previewer, please get the latest code from this Github repo and try again.

**Comment by madamm91** [comment]
Thank you @oliverou and @XietongLU and others for the fix. Now it is working with:

DJI iOS SDK : 4.2.2 (with fixed VideoPreviewer)
DJI Product : Mavic Pro
iOS system version : iOS 11 Beta 6
iOS device type : iPhone 7
Xcode version : Version 9.0 beta 6 (9M214v)

Although the message "Main Thread Checker: UI API called on a background thread: -[UIView layer]" is still appearing in the log, but the video feed seems working.
