### ISSUE TITLE
DJIMissionControlTimeline Command cannot be executed

### ISSUE THREAD

**Issue by ottisoftware** [dji-sdk/Mobile-SDK-iOS#98]
Hello,
I am working on an App that uses DJIMissionControlTimeline to fly 1. a waypoint mission 2. a Hotpoint Mission, 3. DJIGoToAction, 4 DJIGoToAction
It is working till the Hotpoint mission is completed:
Error Domain=DJISDKMissionErrorDomain Code=-5024 "Command cannot be executed.(code:-5024)" UserInfo={NSLocalizedDescription=Command cannot be executed.(code:-5024)}

Step 3. will still be executed.
Notice that step 3. and 4. can also be Waypoint Missions and it will still fail.
I am using DJI SDK 4.0.1, iPhone 6s Plus, Xcode 8.3.1

**Comment by zoemcateedji** [comment]
Thanks @ottisoftware . This issue is reproduced. We fixed it internally just now and it will be included in the next release.

**Comment by dbaldwin** [comment]
@zoemcateedji do you have an estimate on when the next release will be available. We are plagued by several bugs and it would be nice to know. Thank you.

**Comment by zoemcateedji** [comment]
The targeted goal is in the next couple of weeks - we hear you!

**Comment by chasemgray** [comment]
Has this issue been fixed? We are seeing this constantly when trying to upload waypoint missions

**Comment by chasemgray** [comment]
With sdk 4.1.1

**Comment by athiercelin** [comment]
@chasemgray It has been fixed. Are you checking the upload progress of the waypoint and see if an error occured?

**Comment by jane-green** [comment]
Hi,
We are experiencing the same issue - the SDK version we use is also the latest - 4.1.1. Have you found a workaround? 
Thank you.

**Comment by oliverou** [comment]
Hi @jane-green , we have published the latest SDK 4.2 last Friday, could you try it and check if the issue still exist? Thanks!

**Comment by jane-green** [comment]
Hi @oliverou - thanks for the response. Yes, we will certainly give it a try with SDK 4.2 and let you know of the outcome. Thank you.

**Comment by chasemgray** [comment]
We still see this problem regularly. It's most often returned during waypoint upload calls, but sometimes it can be returned for other things such as retrieving no fly zones, etc. We have so many users hitting this issue and it's only appeared in sdk 4.0. Please investigate it.

**Comment by myboyhood** [comment]
I have met this problem, and I give my 3 resolutions
## my env
Xcode 11.7, DJISDK 4.13 ,running GSDemo from dji-mobile-sdk-tutorial
## 1.
 my method is check if the flight is still connected with your App, because if there is a long time no action with aircraft. the aircraft may lose connection with App. my suggestion is before you upload missionPoints, switch to DJI GO 4 App to check the aircraft staying in "ready to fly（开始飞行）" state. if the state of "into aircraft（连接设备）" means not conneting with  the aircraft.

## 2. 
But, my bug is my mission waypoints not conform to DJI  missionPoint defined requirements. such as your the number of waypoint is not correct, or your struct is not correct.
 
## 3.
DJI dev support give my suggestion to check aircraft state before upload mission waypoints, see website here: 
[link](https://developer.dji.com/api-reference/ios-api/Components/Missions/DJIWaypointMissionOperator.html#djiwaypointmissionoperator_currentstate_inline)

and DJI says that the frequency of sending message is too high .

## hope these advises can help us!!
